name: Comment on Pull Requests included in Release
description: Comments on pull requests included in a GitHub release.
branding:
  icon: "align-justify"
  color: "blue"
inputs:
  token:
    description: "Personal access token with public_repo permission"
    required: true
  message:
    description: "The message to be included in the comment"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
